---

- name: install systemd
  ansible.builtin.package:
    name: systemd
    state: present

- name: configure systemd-resolved
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
  register: __systemd_resolved_configuration

- name: link /etc/resolv.conf to stub
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
  when: systemd_resolved_dns_stub_listener|bool

- name: link /etc/resolv.conf to full systemd resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  when: not systemd_resolved_dns_stub_listener|bool

- name: enable systemd-resolved service and assure it is started
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: yes
    state: >-
      {{
        __systemd_resolved_configuration.changed |
          default(False) |
          ternary("restarted", "started")
      }}
...
